package models.workflow

object WorkflowConstants {
  val HEADER = """<?xml version="1.0" encoding="UTF-8"?>"""
  val FIELD = "field"
  val ATTR_ID = "@id"
  val ATTR_REQUIRED = "@required"
  val WORKFLOW_STATE_LOG_MESSAGE = "set models.workflow state: "
  val WORKFLOW = "workflow"
  val WORKFLOW_ACTION_COMMENT = "field-models.workflow-action-comment"
  val WORKFLOW_NAME_EMPTY = "empty_name"
  val ATTR_INHERITABLE = "@inheritable"
  val WORKFLOW_ERROR = "workflow_error"
  val WORKFLOW_ROLES = "workflowroles"
  val WORKFLOW_TYPE_EXPLICIT = "workflow_type_explicit"
  val WORKFLOW_TYPE_EMPTY = "workflow_type_empty"
  val WORKFLOW_TYPE_INHERITABLE = "workflow_type_inheritable"
  val WORKFLOW_TYPE_INHERITED = "workflow_type_inherited"
  val NOTIFICATIONS = "notifications"
  val ATTR_INIT_STATE = "@initial-status"
  val ATTR_INIT_ACTION = "@initial-action"
  val ATTR_NAME = "@name"
  val ATTR_SEND_WITH_EMAIL = "@send_with_email"
  val ATTR_SAVE_AS_PROPERTY = "@save_as_property"
  val EMPTY = "empty"
  val STATE = "state"
  val ATTR_ACTION = "@action"
  val ATTR_FROM = "@from"
  val ATTR_TO = "@to"
  val FIELDS = "fields"
  val ATTR_TYPE = "@type"
  val TRANSITIONS = "transitions"
  val TRANSITION = "transition"
  val ACTIONS = "actions"
  val ACTION = "action"
  val ROLES = "roles"
  val ROLE = "role"
  val REQUIRED = "required"
  val FLOWACTION = "flowaction"
}